### ISSUE TITLE
stucker in codes

### ISSUE THREAD

**Issue by lmlyzxiaop** [bxshi/ConMask#3]
```bash
lab@matrix4:~/lyz$ git clone https://github.com/bxshi/ConMask.git
Cloning into 'ConMask'...
remote: Counting objects: 117, done.
remote: Total 117 (delta 0), reused 0 (delta 0), pack-reused 117
Receiving objects: 100% (117/117), 85.09 KiB | 49.00 KiB/s, done.
Resolving deltas: 100% (49/49), done.
Checking connectivity... done.
lab@matrix4:~/lyz$ cd ConMask/
lab@matrix4:~/lyz/ConMask$ ls
ndkgc  README.md  tools
lab@matrix4:~/lyz/ConMask$ mkdir data
lab@matrix4:~/lyz/ConMask$ ls
data  ndkgc  README.md  tools
lab@matrix4:~/lyz/ConMask$ cd ../
lab@matrix4:~/lyz$ mv dbpedia50 dbpedia500 ./ConMask/data
lab@matrix4:~/lyz$ mv checkpoint_db50_v2_dr_uniweight_2 ./ConMask/
lab@matrix4:~/lyz$ cd ConMask/
lab@matrix4:~/lyz/ConMask$ ls
checkpoint_db50_v2_dr_uniweight_2  data  ndkgc  README.md  tools
lab@matrix4:~/lyz/ConMask$ cd ndkgc/
lab@matrix4:~/lyz/ConMask/ndkgc$ cd ops/
lab@matrix4:~/lyz/ConMask/ndkgc/ops$ ls
content.py     __init__.py  multigpu.py  sampling.py
corruption.py  lookup.py    __sampling
lab@matrix4:~/lyz/ConMask/ndkgc/ops$ cd __sampling/
lab@matrix4:~/lyz/ConMask/ndkgc/ops/__sampling$ ls
CMakeLists.txt  pairwise_sampler.cpp
lab@matrix4:~/lyz/ConMask/ndkgc/ops/__sampling$ cmake .
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- OS Type: Linux
-- TensorFlow include dir: /home/lab/anaconda3/lib/python3.6/site-packages/tensorflow/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lab/lyz/ConMask/ndkgc/ops/__sampling
lab@matrix4:~/lyz/ConMask/ndkgc/ops/__sampling$ cmake --build .
Scanning dependencies of target sampling
[ 50%] Building CXX object CMakeFiles/sampling.dir/pairwise_sampler.cpp.o
[100%] Linking CXX shared library libsampling.so
[100%] Built target sampling
lab@matrix4:~/lyz/ConMask/ndkgc/ops/__sampling$ cd ../../
lab@matrix4:~/lyz/ConMask/ndkgc$ cd ../
lab@matrix4:~/lyz/ConMask$ source activate root
(base) lab@matrix4:~/lyz/ConMask$ python3 -m ndkgc.models.fcn_model_v2 checkpoint_db50_v2_dr_uniweight_2 data/dbpedia50 --force_eval --layer 3 --conv 2 --lr 1e-2 --keep_prob 0.5 --max_content 512 --pos 1 --neg 4 --open --neval 5000 --eval --filter
Traceback (most recent call last):
  File "/home/lab/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lab/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lab/lyz/ConMask/ndkgc/models/fcn_model_v2.py", line 6, in <module>
    from ndkgc.models.content_model import ContentModel
  File "/home/lab/lyz/ConMask/ndkgc/models/content_model.py", line 6, in <module>
    from ndkgc.ops import *
  File "/home/lab/lyz/ConMask/ndkgc/ops/__init__.py", line 1, in <module>
    from ndkgc.ops.corruption import *
  File "/home/lab/lyz/ConMask/ndkgc/ops/corruption.py", line 6, in <module>
    from ndkgc.ops.sampling import single_negative_sampling, multiple_negative_sampling
  File "/home/lab/lyz/ConMask/ndkgc/ops/sampling.py", line 5, in <module>
    __lib = tf.load_op_library(os.path.join(__so_dir, './__sampling/libsampling.so'))
  File "/home/lab/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /home/lab/lyz/ConMask/ndkgc/ops/./__sampling/libsampling.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumE
```

**Comment by bxshi** [comment]
Hi I noticed that you run activate root after compiling the op. Could you activate your venv first and then compile the op?

**Comment by lmlyzxiaop** [comment]
I already tried activate my env first . But I get the same error

**Comment by bxshi** [comment]
When you activate your env first, have you deleted all CMake temporary files in the `sampling` folder and do a clean make&build?

It seems that the program cannot find the symbol defined in `tensorflow/core/lib/strings/strcat.h`. Would you mind to check if the TensorFlow located at `/home/lab/anaconda3/lib/python3.6/site-packages/tensorflow/include` is the same as the one you are using in your venv?

I was using Python3.4 while developing this, so you might want to try downgrade your Python to 3.4 and try again. Although I don't think this would be the cause.

**Comment by lmlyzxiaop** [comment]
I create a new env with python3.4 and tensorflow1.3 and reclone the project and do make and build. And I still get the same error.

**Comment by lmlyzxiaop** [comment]
this command solve my problem ,  g++ -g -std=c++11 -I '/home/lab/anaconda3/envs/py3/lib/python3.4/site-packages/tensorflow/include' -D_GLIBCXX_USE_CXX11_ABI=0 pairwise_sampler.cpp -fPIC -shared -pthread -O2 -o libsampling.so

**Comment by bxshi** [comment]
Good to know, and thanks for posting your solution here!
